<h1>Objective</h1>

The objective is to learn basic image processing skills to achieve computer vision using OpenCV library in Python.

**Author :** Ronak Patel

**Reference :** LinkedIn Learning, OpenCV for Python Developers

In [1]:
# imports
import cv2
import numpy as np

# Basic Image Operations

## Accessing an Image

In [3]:
# read an image
img = cv2.imread("Scarlet-Macaws.png")

# show an image in a window
cv2.namedWindow("Image", cv2.WINDOW_NORMAL)
cv2.imshow("Image", img)

# wait indefinitely for a key to be pressed to exit the window, change 0 value to wait temporarily
cv2.waitKey(0)

# close all image windows
cv2.destroyAllWindows() 

In [4]:
# write an image
cv2.imwrite("Scarlet-Macaw2.png", img)

True

## Understanding Pixel Data

In [5]:
# read an image in color
img_color = cv2.imread("Scarlet-Macaws.png", 1)

# read an image in grayscale
img_grayscale = cv2.imread("Scarlet-Macaws.png", 0)

# show images
cv2.namedWindow("Color Image", cv2.WINDOW_NORMAL)
cv2.namedWindow("Grayscale Image", cv2.WINDOW_NORMAL)

cv2.imshow("Color Image", img_color)
cv2.imshow("Grayscale Image", img_grayscale)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# image dimensions
print(f"Size of grayscale image : {img_grayscale.shape}")
print(f"Size of color image \t: {img_color.shape}")

Size of grayscale image : (428, 419)
Size of color image 	: (428, 419, 3)


**NOTE :**
- We can see that the grayscale image shows 2 coordinates (2D image). OpenCV shows this in (height, width) format.
  The color image shows 3 coordinates (3D image), shown as (height, width, channels).

In [9]:
# seeing pixel data
img_grayscale

array([[216, 216, 216, ..., 218, 218, 218],
       [216, 216, 216, ..., 218, 218, 218],
       [216, 216, 216, ..., 218, 218, 218],
       ...,
       [215, 215, 215, ..., 216, 216, 216],
       [215, 215, 215, ..., 216, 216, 216],
       [215, 215, 215, ..., 216, 216, 216]], dtype=uint8)

In [10]:
img_color

array([[[219, 213, 224],
        [219, 213, 224],
        [219, 213, 224],
        ...,
        [216, 210, 235],
        [216, 210, 235],
        [216, 210, 235]],

       [[219, 213, 224],
        [219, 213, 224],
        [219, 213, 224],
        ...,
        [216, 210, 235],
        [216, 210, 235],
        [216, 210, 235]],

       [[219, 213, 224],
        [219, 213, 224],
        [219, 213, 224],
        ...,
        [216, 210, 235],
        [216, 210, 235],
        [216, 210, 235]],

       ...,

       [[224, 218, 206],
        [224, 218, 206],
        [224, 218, 206],
        ...,
        [219, 213, 224],
        [219, 213, 224],
        [219, 213, 224]],

       [[224, 218, 206],
        [224, 218, 206],
        [224, 218, 206],
        ...,
        [219, 213, 224],
        [219, 213, 224],
        [219, 213, 224]],

       [[224, 218, 206],
        [224, 218, 206],
        [224, 218, 206],
        ...,
        [219, 213, 224],
        [219, 213, 224],
        [219, 213, 224]]

In [11]:
# height of the image; number of pixels in a column or number of rows in an image
print(f"Image height \t\t: {len(img_color)}")

# width of an image; number of pixels in a row or number of columns in an image
# looking at the top row specifically (0)
print(f"Image width \t\t: {len(img_color[0])}")

# number of channels in an image
print(f"Number of channels \t: {len(img_color[0][0])}")

# shape of an image; [height, width, number of channels]
print(f"Image Shape \t\t: {img_color.shape}")

Image height 		: 428
Image width 		: 419
Number of channels 	: 3
Image Shape 		: (428, 419, 3)


In [13]:
# datatype of image
# ('uint8'); this tells us there are a maximum of 2**8 (256) values in each pixel of this image
# range of values from 0 to 255
print(f"Image datatype \t\t: {img_color.dtype}")

# show pixel values at 10th row and 5th column
print(f"Pixel values at [10, 5] : {img_color[10, 5]}")

# show pixel values in a channel
print("\n")
print(f"Pixel values in Blue channel \t: \n{img_color[:, :, 0]}\n")
print(f"Pixel values in Green channel \t: \n{img_color[:, :, 1]}\n")
print(f"Pixel values in Red channel \t: \n{img_color[:, :, 2]}")

# show total number of pixel values in an image
print(f"\nImage total pixel values : {img_color.size}")

Image datatype 		: uint8
Pixel values at [10, 5] : [219 213 224]


Pixel values in Blue channel 	: 
[[219 219 219 ... 216 216 216]
 [219 219 219 ... 216 216 216]
 [219 219 219 ... 216 216 216]
 ...
 [224 224 224 ... 219 219 219]
 [224 224 224 ... 219 219 219]
 [224 224 224 ... 219 219 219]]

Pixel values in Green channel 	: 
[[213 213 213 ... 210 210 210]
 [213 213 213 ... 210 210 210]
 [213 213 213 ... 210 210 210]
 ...
 [218 218 218 ... 213 213 213]
 [218 218 218 ... 213 213 213]
 [218 218 218 ... 213 213 213]]

Pixel values in Red channel 	: 
[[224 224 224 ... 235 235 235]
 [224 224 224 ... 235 235 235]
 [224 224 224 ... 235 235 235]
 ...
 [206 206 206 ... 224 224 224]
 [206 206 206 ... 224 224 224]
 [206 206 206 ... 224 224 224]]

Image total pixel values : 537996
